### ISSUE TITLE
Roadmap/Todo lists

### ISSUE THREAD

**Issue by chenx6** [chenx6/wasmdori#1]
- [x] Profile manager/toolkit
- [x] Append data to origin profile
- [x] Gacha calendar
- [ ] Rearrange help text, rearrange style of the help
- [ ] ARCHITECTURE.md
- [ ] Unit test
- [x] ~CI auto update data~
  - Upstream datasource (Bestdori) may change data format, so it should be reconsider
- [x] ~Data inspector based on SQL database~
  - Not so important...
  - Maybe we should use [phiresky/sql.js-httpvfs](https://github.com/phiresky/sql.js-httpvfs)
